In [18]:
print("hello")

hello


In [ ]:
pip install pandas

In [20]:
a = float(input("enter a number"))
print(a)

enter a number5
5.0


In [21]:
b =int(input("enter a number"))
print(b
      )

enter a number5
5


In [22]:
c=int(input("enter a number a="))
print(c)
d=int(input("enter a number b="))
print(d)
print(c+d)

enter a number a=5
5
enter a number b=6
6
11


In [24]:
import pandas as pd
import numpy as np
a = np.array([1,5,87])
print(a)

[ 1  5 87]


In [26]:
import numpy as np
b = np.array([list({4,54,21,6,6}),[4,52,4,2]])
print(b)

[[ 4 21 54  6]
 [ 4 52  4  2]]


In [29]:
import numpy as np
a = np.array([[1,5,65],[5,65,8]])
print(a.ndim)

2


In [30]:
a = np.array([[1,5,65],[5,65,8]])
print(a.size)

6


In [31]:

a = np.array([[1,5,65],[5,65,8]])
print(a.dtype)

int64


In [33]:
a=np.arange(1,52)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51]


In [34]:
a=np.arange(1,52,3)
print(a)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


In [38]:
a=np.array([1,5,2,12,54,5,6,2,8])
print(a.max())

54


In [41]:
from numpy._core.fromnumeric import reshape
a=np.arange(1,13)
print(a.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [42]:
a=np.array([1,5,2,12,54,5,6,2,8])
print(a.max(),a.sum())

54 95


In [43]:
a=np.array([[1,5,65],[5,65,8]])
print(a.max())
print(a.min(),a.max())
print(a.sum(),a.mean())

65
1 65
149 24.833333333333332


In [44]:
a=np.array([1,5,2,12,54,5,6,2,8])
print(a.max()*2)

108


In [45]:
a=np.array([1,5,2,12,54,5,6,2,8])
print(a.min()/2)

0.5


In [46]:
a=np.array([1,5,2,12,54,5,6,2,8])
print(a[2])

2


In [47]:
a=np.array([1,5,2,12,54,5,6,2,8])
print(a[3])

12
